### ISSUE TITLE
Some bugs to fix

### ISSUE THREAD

**Issue by sagitaire123** [2Checkout/woocommerce#1]
Hello,

**First problem :** 

I'm using 2Checkout Inline and ConvertPlus, there's a problem when we try to complete a purchase for a pending order that we have on "My Account > My Orders", when we click on pay on woocommerce we are redirected to : 
https://website.com/checkout/order-pay/2948/?pay_for_order=true&key=wc_order_XXXXXXXX

From this page, it's not possible to make a payment, the popup to make the payment is not opened and we are redirected to a blank page.

**Second Problem :**

In case you're using this plugin, at WC checkout page if you select (ConvertPlus/Inline/2PayJS) and you change your mind and you want to select another Payment Method like PayPal for example, it will not work, the redirection to PayPal don't work after clicking on "Complete payment", some JS errors occur.

Thank you

**Comment by DAHcod** [comment]
Same problem. I wish some body else fix these as soon as possible.

**Comment by sagitaire123** [comment]
They are already working on it, it will be ready today or tomorrow.

**Comment by DAHcod** [comment]
A good news. I am looking forward to fixing it ASAP.
Thank you.

**Comment by sagitaire123** [comment]
If you noticed another problem, publish it.
For your case you have the 2 problems ?

**Comment by DAHcod** [comment]
I have an other problem: When I activate this plugin, at line IPN Callback Url was generated the link with **http**://www...not **https**://www...because my site is support SSL. This maybe an error for processing payments.

**Comment by sagitaire123** [comment]
Yes, same problem here.
But it seems it doesn't affect processing payments, i made some tests, but i think it's better to make it https

**Comment by DAHcod** [comment]
I have tested and it showed this red message: " X Error when trying to place order" at the page https://www.mywebsite.com/my-account/
I think this problem need to test carefully and fix it soon.

**Comment by sagitaire123** [comment]
@DAHcod Can you send a screenshot here of the error ?

**Comment by DAHcod** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/72394880/95105787-834f6880-06ec-11eb-9297-af8f408b1d91.png)
![Screenshot (23)](https://user-images.githubusercontent.com/72394880/95105792-85192c00-06ec-11eb-9634-e25034286ee6.png)
![Screenshot (24)](https://user-images.githubusercontent.com/72394880/95105797-85b1c280-06ec-11eb-86b4-cc568a0b790b.png)
I have other problems as screenshot files attached. I hope all these will be fix soon.

**Comment by sagitaire123** [comment]
For the first screenshot, it's normal, PayPal is not enabled on your 2Checkout account.
For second screenshot, 2Checkout need to fix the page of privacy policy etc..., but it's not a major problem.
For the 3rd screenshot, at which moment this message is displayed, just when you access to my account page ?

**Comment by DAHcod** [comment]
For the 3rd screenshot, at which moment this message is displayed, just when you access to my account page ?
Answer: When I tested place order, after loading the checkout payment and then closed it. After that I go to my account page to see my pending order and it displayed the error message.
I think this issue maybe at line IPN Callback Url was generated the link with **http**://www...not **https**://www...because my site is support SSL. This maybe an error for processing payments

**Comment by DAHcod** [comment]
Do let me know if your 2 problem have been resolved.

**Comment by DAHcod** [comment]
Do you have any information for your 2 problem have been resolved?

**Comment by sagitaire123** [comment]
The problem of switching to another payment method, is already fixed here : https://github.com/2Checkout/woocommerce/tree/release

**Comment by DAHcod** [comment]
> Hello,
> 
> **First problem :**
> 
> I'm using 2Checkout Inline and ConvertPlus, there's a problem when we try to complete a purchase for a pending order that we have on "My Account > My Orders", when we click on pay on woocommerce we are redirected to :
> https://website.com/checkout/order-pay/2948/?pay_for_order=true&key=wc_order_XXXXXXXX
> 
> From this page, it's not possible to make a payment, the popup to make the payment is not opened and we are redirected to a blank page.
> 
> **Second Problem :**
> 
> In case you're using this plugin, at WC checkout page if you select (ConvertPlus/Inline/2PayJS) and you change your mind and you want to select another Payment Method like PayPal for example, it will not work, the redirection to PayPal don't work after clicking on "Complete payment", some JS errors occur.
> 
> Thank you

Did you fix your issue?

**Comment by sagitaire123** [comment]
The second problem yes, it's already fixed, the first one not yet.
@craigchristenson The my account problem will be fixed soon ?

**Comment by DAHcod** [comment]
I am waiting the first one as well

**Comment by DAHcod** [comment]
Hi,
Do you know how long take to get the first one fixed?

**Comment by sagitaire123** [comment]
No idea

**Comment by craigchristenson** [comment]
Sorry for the delay, a patch for the 'My Account' issue was just pushed to the release branch. Please let me know if you find any issues.
https://github.com/2Checkout/woocommerce/tree/release

**Comment by DAHcod** [comment]
Hello,

I have updated but it seems still not working yet. Please tell how to do update to it works on my site?

**Comment by DAHcod** [comment]
The popup to make the payment is not opened and I am still redirected to a blank page as the first one from sagitaire123
Please check and tell me how to do?

**Comment by sagitaire123** [comment]
@DAHcod i updated the plugin and it seems working perfectly without any problem, now i'm making tests to be sure that there's no bugs.

**Comment by sagitaire123** [comment]
@craigchristenson , i detected a 

> Sorry for the delay, a patch for the 'My Account' issue was just pushed to the release branch. Please let me know if you find any issues.
> https://github.com/2Checkout/woocommerce/tree/release

@craigchristenson after making some tests, there's a problem at the moment we try to make a payment from "My Account" page, when we select for example 2Checkout Inline and the Popup is open, if we close it and we want to change and choose another payment method and click on "Complete Payment", the Popup of 2Checkout Inline will be opened everytime, even if another payment method is selected.

**Comment by DAHcod** [comment]
@craigchristenson I have tested this on mobile but there was a error with message: "**Error processing checkout. Please try again.**"
@sagitaire123 Can you check and confirm this problem is correct please?

**Comment by sagitaire123** [comment]
@DAHcod Are you talking about my account page on mobile ?

**Comment by DAHcod** [comment]
@sagitaire123 That is when I use my mobile to checkout and choose 2Checkout Inline to pay. But it seems not support and showed the error message.

**Comment by sagitaire123** [comment]
@DAHcod which mobile are using and which browser ?

**Comment by DAHcod** [comment]
@sagitaire123 iPhone with safari browser.

**Comment by sagitaire123** [comment]
Which iPhone ?

**Comment by DAHcod** [comment]
> Which iPhone ?

XS max

**Comment by sagitaire123** [comment]
I will try tomorrow and let you know

**Comment by Sonansh** [comment]
It's ridiculous to see that the live plugin has such a basic error. I was wondering why I am not receiving any order via 2checkout for 1 month. Found this crap today.

@sagitaire123 , I confirm I have the same experience as you.  Can you please confirm if all the errors such as the "blank page" issue are resolved now?

Thanks

**Comment by sagitaire123** [comment]
@sagitaire123 Yes it has been resolved on My Account page, but still there's some bug.

**Comment by Sonansh** [comment]
So you mean these are solved
1) Blank page issue
2) Account page

Then which issues are left?

**Comment by Sonansh** [comment]
I have updated the 2checkout inline and it still throws the blank page. The version of the plugin says 0.0.3

Can you please confirm if you have installed the same version?

**Comment by DAHcod** [comment]
I still have Blank page issue and checkout by mobile issue.

**Comment by sagitaire123** [comment]
Use this release https://github.com/2Checkout/woocommerce/tree/release
it was published by @craigchristenson 

it still have some small bugs, normally he told me that it will be fixed this Monday.

**Comment by Sonansh** [comment]
Thanks @sagitaire123 for sending that link.

I checked both express and Inline methods. Inline worked but express didn't.  However, I prefer inline more. But that's a note to mention.

Can you please briefly tell me what small bugs are remaining so I could also track at my end ?

Thank you

**Comment by sagitaire123** [comment]
@Sonansh Personnally i'm using 2Checkout Inline, and it's working good and prefer it comparing to others solutions.

For the small bugs, it's mentioned here, @craigchristenson told me that it will be fixed soon, maybe this monday :

> @craigchristenson after making some tests, there's a problem at the moment we try to make a payment from "My Account" page, when we select for example 2Checkout Inline and the Popup is opened, if we decide to close it and we want to change and choose another payment method and click on "Complete Payment", the Popup of 2Checkout Inline will be opened everytime, even if another payment method is selected.

**Comment by Sonansh** [comment]
I also believe there is some inconsistency with 3D secure pin as well. Hope this plugin becomes fixed soon.

**Comment by sagitaire123** [comment]
@Sonansh what do you mean exactly ?

**Comment by Sonansh** [comment]
After the customer enters the card number, he/she should receive the 6 digit code from the bank which should be entered in order to complete the payment. This number is called 3D secure pin.

The plugin either doesn't sends the pin or is not able to verify when the customer enters.

**Comment by sagitaire123** [comment]
@Sonansh This part normally is not managed by the plugin, but by the customer bank, it's the bank who send the 6 digit code, and it's also the bank who approve or not the payment before redirecting to 2Checkout.

**Comment by DAHcod** [comment]
@sagitaire123 @craigchristenson Is there any new updates?

**Comment by craigchristenson** [comment]
@sagitaire123 the fix for inline being invoked after another payment method was selected has been pushed to the release branch.
@Sonansh @DAHcod the 3DS, PayPal and privacy policy issues that you are reporting are not part of this plugin but they may be an issues in the 2Checkout inline checkout. Can you both open a support tickets with 2Checkout Support? I can make sure that they receive the proper attention to investigate.

**Comment by DAHcod** [comment]
@craigchristenson Can you change when I click place order first iFrame displayed to choose "How will you pay?" options Credit card or PayPay as the attached file?
![Screenshot (35)_LI](https://user-images.githubusercontent.com/72394880/95811251-b59e2e80-0cc7-11eb-9703-5cad673e777a.jpg)

**Comment by sagitaire123** [comment]
@DAHcod when you say if he can change it, you want to change by what exactly ?

**Comment by Sonansh** [comment]
@craigchristenson 

1) I have updated the plugin from this link - https://github.com/2Checkout/woocommerce/tree/release. Is it correct link?
2) I will perform few more tests and if I still face 3D secure pin issue, I will create a new ticket. 
3) Can you please publish this plugin to Wordpress Directory? So auto-update is more streamlined?
4) Since past 3 updates, the plugin version is still 0.0.3. Please keep on upgrading that number so we can track and know what we are doing.
5) How do I change the color of the 2checkout inline primary button like @DAHcod  showed in the pic? In my case it is green and it does not looks good with my theme colors. See image.
![color](https://user-images.githubusercontent.com/14956505/95876225-77b90d00-0d90-11eb-9068-948a954b44a3.JPG)

**Comment by sagitaire123** [comment]
@DAHcod For me for example, i don't have PayPal on 2Checkout so it ask client to put his credit card numbers directly, at the final step, and it's better like that for my case.

@Sonansh i think @craigchristenson didn't change the version of the plugin yet because it's only a release version, it was not committed yet until we make enough tests.
For 3D secure, i have clients who are making payments through 2Checkout Inline and they didn't face any problem with 3D secure, i didn't get any complains about that.
For the colors, @DAHcod didn't change anything, it's the default color of the first and second step, and the third step is green, that's normal. 
you need to understand that the box of 2Checkout Inline is not really implemented on the plugin, it's only a request sent to 2Checkout to display it on our website, so it's managed by 2Checkout and not the plugin. @craigchristenson can confirm if i'm right.

**Comment by Sonansh** [comment]
@sagitaire123 , When I downloaded the CSV report of recent failed orders, all of them said "unfinished" on the 3D secure column in that excel report. That's why I was concerned. However, when I myself did a test payment, 3D secure worked.
![3Ds](https://user-images.githubusercontent.com/14956505/95884561-e2bb1180-0d99-11eb-9e3c-1ee2f0404301.JPG)


For the color, yes it appears to be controlled by 2checkout and not the plugin. But I think there should be an option to control that color from 2checkout admin.

**Comment by sagitaire123** [comment]
@craigchristenson i made tests of the last release, the problem of switching to other payment method is fixed on "My Account" page, but now the same problem is on "Checkout" page, the problem just changed pages lol

**Comment by DAHcod** [comment]
> @DAHcod For me for example, i don't have PayPal on 2Checkout so it ask client to put his credit card numbers directly, at the final step, and it's better like that for my case.
> 
> @Sonansh i think @craigchristenson didn't change the version of the plugin yet because it's only a release version, it was not committed yet until we make enough tests.
> For 3D secure, i have clients who are making payments through 2Checkout Inline and they didn't face any problem with 3D secure, i didn't get any complains about that.
> For the colors, @DAHcod didn't change anything, it's the default color of the first and second step, and the third step is green, that's normal.
> you need to understand that the box of 2Checkout Inline is not really implemented on the plugin, it's only a request sent to 2Checkout to display it on our website, so it's managed by 2Checkout and not the plugin. @craigchristenson can confirm if i'm right.

For this only when you click icon Cart on your 2Checkout inline you can see PayPal option. I want to the first step our customers can see 2 choice Credit card or PayPal and they will choose payment method first like the photo I attached before.

**Comment by sagitaire123** [comment]
@DAHcod That's not an issue i think but it's a new feature, it must be an option on the plugin (to choose which page we want to see first), so you can make the proposal to 2Checkout, and maybe it will be done on the next version.
For my case, i don't really need it, as i have only Credit Card.

**Comment by Sonansh** [comment]
@DAHcod I keep a dedicated option for Paypal active which comes default in woocommerce. That is probably the best solution for paypal. I use 2checkout only for credit cards. However it offers a paypal option too. That's just an extra good thing for me. But for Paypal I prefer a default option active.

So at checkout, I offer two separate payment options.
1) Paypal by woocommerce default
2) 2checkout (which also includes a paypal option)

@sagitaire123  I will check and update

**Comment by DAHcod** [comment]
> @DAHcod That's not an issue i think but it's a new feature, it must be an option on the plugin (to choose which page we want to see first), so you can make the proposal to 2Checkout, and maybe it will be done on the next version.
> For my case, i don't really need it, as i have only Credit Card.

Really I think it has been already integrated. You can click on my circle as the attached photo.

 
![Uploading 99B6B759-7928-492E-8888-4EB7B1E745B4.jpeg…]()

**Comment by sagitaire123** [comment]
@Sonansh @DAHcod 
@craigchristenson pushed a new version : https://github.com/2Checkout/woocommerce/tree/release
it seems working good now, you can make tests from your side and confirm.

**Comment by DAHcod** [comment]
@craigchristenson Can you make my issue please? I want to it shows first start: 
Cart --> Billing --> Payment (See photo 1). 
This plugin now is showed Payment first (See photo 2). 
No any any option for choose when it displays first.
@sagitaire123 I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)

![Photo 1](https://user-images.githubusercontent.com/72394880/96100767-951dd200-0e89-11eb-86d9-1e6aee7660c3.png)

![Photo 2](https://user-images.githubusercontent.com/72394880/96100862-ad8dec80-0e89-11eb-962e-7b1bdd30f4bd.png)

**Comment by Sonansh** [comment]
Hi @sagitaire123 and @craigchristenson 

I have tested the plugin on the remaining issues. The gateways now successfully works from "My account" and re-works again on checkout page.

However, I realized that your old plugin has a smart functionality that is missing in this version.

Old plugin - https://docs.woocommerce.com/document/2checkout-inline-checkout/

Functionality misssing:

If the person does't want to procced to checkout after he has started the proccess maybe because he wants to edit items in his cart. The old plugin still restores the cart is the person went back from the checkout. But this plugin clears the cart.

I would appreciate if this functianlity is considered.

**Comment by DAHcod** [comment]
> @craigchristenson Can you make my issue please? I want to it shows first start:
> Cart --> Billing --> Payment (See photo 1).
> This plugin now is showed Payment first (See photo 2).
> No any option Credit and PayPal for users to choose when it displays first. I want users can see first 2 option Credit and PayPal when popup displayed first like photo 1.
> 
> @sagitaire123, I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)
> 
> ![Photo 1](https://user-images.githubusercontent.com/72394880/96101169-0a89a280-0e8a-11eb-99fc-bf6c4af5bb83.png)
> 
> ![Photo 2](https://user-images.githubusercontent.com/72394880/96101197-107f8380-0e8a-11eb-921c-afeb2fcdf905.png)

@craigchristenson Can you do my issue please?

**Comment by craigchristenson** [comment]
> https://docs.woocommerce.com/document/2checkout-inline-checkout/

In my testing with the inline module, I can bring up inline, close it, go back to my cart to edit/add items and bring up inline again to pay for the current cart. It could be that you do not have the latest release or that I don't understand the feature request. I merged the release branch to master today. When you get a chance can you please confirm that you still have this issue on the current release?

**Comment by craigchristenson** [comment]
> > @craigchristenson Can you make my issue please? I want to it shows first start:
> > Cart --> Billing --> Payment (See photo 1).
> > This plugin now is showed Payment first (See photo 2).
> > No any option Credit and PayPal for users to choose when it displays first. I want users can see first 2 option Credit and PayPal when popup displayed first like photo 1.
> > @sagitaire123, I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)
> > ![Photo 1](https://user-images.githubusercontent.com/72394880/96101169-0a89a280-0e8a-11eb-99fc-bf6c4af5bb83.png)
> > ![Photo 2](https://user-images.githubusercontent.com/72394880/96101197-107f8380-0e8a-11eb-921c-afeb2fcdf905.png)
> 
> @craigchristenson Can you do my issue please?

This is happening because the plugin uses the 2Checkout Inline Auto Advance feature.
https://knowledgecenter.2checkout.com/Documentation/07Commerce/InLine-Checkout-Guide/Turn-on-auto-advance-feature
I will make sure that we make this configurable in a future release, in the meantime you can remove this line to get the behavior you want.
https://github.com/2Checkout/woocommerce/blob/69fe92af8b498a6869a1eb7f00b6c9bfbdbd4f37/twocheckout-inline/assets/js/twocheckout_inline.js#L54

**Comment by DAHcod** [comment]
> > > @craigchristenson Can you make my issue please? I want to it shows first start:
> > > Cart --> Billing --> Payment (See photo 1).
> > > This plugin now is showed Payment first (See photo 2).
> > > No any option Credit and PayPal for users to choose when it displays first. I want users can see first 2 option Credit and PayPal when popup displayed first like photo 1.
> > > @sagitaire123, I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)
> > > ![Photo 1](https://user-images.githubusercontent.com/72394880/96101169-0a89a280-0e8a-11eb-99fc-bf6c4af5bb83.png)
> > > ![Photo 2](https://user-images.githubusercontent.com/72394880/96101197-107f8380-0e8a-11eb-921c-afeb2fcdf905.png)
> > 
> > 
> > @craigchristenson Can you do my issue please?
> 
> This is happening because the plugin uses the 2Checkout Inline Auto Advance feature.
> https://knowledgecenter.2checkout.com/Documentation/07Commerce/InLine-Checkout-Guide/Turn-on-auto-advance-feature
> I will make sure that we make this configurable in a future release, in the meantime you can remove this line to get the behavior you want.
> https://github.com/2Checkout/woocommerce/blob/69fe92af8b498a6869a1eb7f00b6c9bfbdbd4f37/twocheckout-inline/assets/js/twocheckout_inline.js#L54

I have removed line 54 like you said but nothing change. Still same issue.
Please do let me know more.
Thank you.

**Comment by craigchristenson** [comment]
> > > > @craigchristenson Can you make my issue please? I want to it shows first start:
> > > > Cart --> Billing --> Payment (See photo 1).
> > > > This plugin now is showed Payment first (See photo 2).
> > > > No any option Credit and PayPal for users to choose when it displays first. I want users can see first 2 option Credit and PayPal when popup displayed first like photo 1.
> > > > @sagitaire123, I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)
> > > > ![Photo 1](https://user-images.githubusercontent.com/72394880/96101169-0a89a280-0e8a-11eb-99fc-bf6c4af5bb83.png)
> > > > ![Photo 2](https://user-images.githubusercontent.com/72394880/96101197-107f8380-0e8a-11eb-921c-afeb2fcdf905.png)
> > > 
> > > 
> > > @craigchristenson Can you do my issue please?
> > 
> > 
> > This is happening because the plugin uses the 2Checkout Inline Auto Advance feature.
> > https://knowledgecenter.2checkout.com/Documentation/07Commerce/InLine-Checkout-Guide/Turn-on-auto-advance-feature
> > I will make sure that we make this configurable in a future release, in the meantime you can remove this line to get the behavior you want.
> > https://github.com/2Checkout/woocommerce/blob/69fe92af8b498a6869a1eb7f00b6c9bfbdbd4f37/twocheckout-inline/assets/js/twocheckout_inline.js#L54
> 
> I have removed line 54 like you said but nothing change. Still same issue.
> Please do let me know more.
> Thank you.

Please try clearing your cache to insure that you are getting the updated JS file and please clear your cookies to remove the previous order session.  `TwoCoInlineCart.cart.setAutoAdvance(true); ` is the setting that skips the first 2 steps of inline checkout.

**Comment by DAHcod** [comment]
> > > > > @craigchristenson Can you make my issue please? I want to it shows first start:
> > > > > Cart --> Billing --> Payment (See photo 1).
> > > > > This plugin now is showed Payment first (See photo 2).
> > > > > No any option Credit and PayPal for users to choose when it displays first. I want users can see first 2 option Credit and PayPal when popup displayed first like photo 1.
> > > > > @sagitaire123, I tested and it seems working but it is better if it goes to first start Cart --> Billing --> Payment (See photo 1)
> > > > > ![Photo 1](https://user-images.githubusercontent.com/72394880/96101169-0a89a280-0e8a-11eb-99fc-bf6c4af5bb83.png)
> > > > > ![Photo 2](https://user-images.githubusercontent.com/72394880/96101197-107f8380-0e8a-11eb-921c-afeb2fcdf905.png)
> > > > 
> > > > 
> > > > @craigchristenson Can you do my issue please?
> > > 
> > > 
> > > This is happening because the plugin uses the 2Checkout Inline Auto Advance feature.
> > > https://knowledgecenter.2checkout.com/Documentation/07Commerce/InLine-Checkout-Guide/Turn-on-auto-advance-feature
> > > I will make sure that we make this configurable in a future release, in the meantime you can remove this line to get the behavior you want.
> > > https://github.com/2Checkout/woocommerce/blob/69fe92af8b498a6869a1eb7f00b6c9bfbdbd4f37/twocheckout-inline/assets/js/twocheckout_inline.js#L54
> > 
> > 
> > I have removed line 54 like you said but nothing change. Still same issue.
> > Please do let me know more.
> > Thank you.
> 
> Please try clearing your cache to insure that you are getting the updated JS file and please clear your cookies to remove the previous order session. `TwoCoInlineCart.cart.setAutoAdvance(true); ` is the setting that skips the first 2 steps of inline checkout.

It works perfectly. Thank you so much.

**Comment by DAHcod** [comment]
Hi @craigchristenson,
I have an issue. At step Pay for order I want users have to tick choose: "I have read and agree to the website terms and conditions" before they submit.
Now my issue no any tick and users still submit. This issue need to fix.

See the attached file.

Thank you.
![Screenshot](https://user-images.githubusercontent.com/72394880/97067616-16edb980-1574-11eb-98c4-70d09cf6a5cb.png)

**Comment by Sonansh** [comment]
Hey @DAHcod, I tested what you say but it's working on my end. I believe it is the basic woocommerce thing and not the 2checkout plugin thing.
![test](https://user-images.githubusercontent.com/14956505/97082786-e6685700-1629-11eb-9cc3-c264b9b74b5a.JPG)

**Comment by DAHcod** [comment]
> Hey @DAHcod, I tested what you say but it's working on my end. I believe it is the basic woocommerce thing and not the 2checkout plugin thing.
> ![test](https://user-images.githubusercontent.com/14956505/97082786-e6685700-1629-11eb-9cc3-c264b9b74b5a.JPG)

Hi @Sonansh,
Please note that this issue happens with "Pay for order" button. Please go to user's account --> orders --> Pay | View | Cancel. You choose "Pay" button and try it. You will have result like me.

**Comment by DAHcod** [comment]
> Hi @craigchristenson,
> I have an issue. At step Pay for order I want users have to tick choose: "I have read and agree to the website terms and conditions" before they submit.
> Now my issue no any tick and users still submit. This issue need to fix.
> 
> See the attached file.
> 
> Thank you.
> ![Screenshot](https://user-images.githubusercontent.com/72394880/97067616-16edb980-1574-11eb-98c4-70d09cf6a5cb.png)

@craigchristenson Do you have any update for this issue?
